### ISSUE TITLE
Add Reservoir Computing

### ISSUE THREAD

**Issue by verzep** [williamgilpin/dysts#2]
Reservoir Computing appears to be the SotA in many tasks involving dynamical systems, it would be interesting to have it among the models.

**Comment by williamgilpin** [comment]
I agree, I would be very interested in getting a head-to-head comparison! Do you know of a standard reservoir computing implementation that I could use as a benchmark? I looked into this a few months ago, and I couldn't find a consensus model to use

**Comment by williamgilpin** [comment]
I agree that a paper doing a serious benchmark bakeoff between reservoir computers, neural ODEs, and general-purpose DNNs would be extremely informative. One metric that would be great to include in such a benchmark would be total compute time, since reservoir computers are so quick to train. I also think that some measure of the stability of the representation (ie, if replicate models are trained on random subsets of train, do they produce similar vector fields?). My intuition is that neural ODEs produce very consistent representations across different datasets

Here's a reservoir computing paper from NeurIPS last year that has some quantification of reservoir size vs accuracy
https://arxiv.org/abs/2006.07310

**Comment by williamgilpin** [comment]
I have now included reservoir computing among the benchmarks. It performs very well, consistently appearing among the top 5 models (and which considerably less training time)
