### ISSUE TITLE
Integration timestep relation to the minimum timescale?

### ISSUE THREAD

**Issue by akaptano** [williamgilpin/dysts#7]
Hi Will,

Hope you're doing well. We are working on a PySINDy + dysts project and are wondering about the precise way the 'dt' parameter is calculated. It appears that the 'period' parameter is the largest timescale in the system, and 'dt' maybe the smallest timescale in the system, although in the paper you refer to instead as "optimal integration timestep", so I'm not sure. For instance, for the AtmosphericRegime my understanding from the Tuwankotta paper is that the fast timescale = 0.01 but for the dysts database dt = 0.01773980357826076. If it is not the smallest timescale, is it close? Is there a good way to calculate the true smallest timescale? Any clarification would be appreciated.

Best,
Alan

**Comment by williamgilpin** [comment]
Hi Alan! I hope that you are doing well. I picked the max and min timescales algorithmically for each system, not using domain knowledge, and so they might deviate from the natural timescales in the system (like the driving period of the blinking vortex and other similar systems). I took a bunch of FFTs from trajectories starting at random initial conditions, and then computed a bunch of surrogate time series to determine which timescales were significant. The timestep was chosen from the largest significant timescale. Since I use a variable-step integrator, this is the largest timestep it would take. The period is the FFT mean.

**Comment by akaptano** [comment]
Thanks very much for this clarification. My understanding is that this method is unsuitable for our purposes -- I am not sure how FFTs can capture the time scales associated with the nonlinearities, for instance. Do you know if there is a systematic way to identify the smallest and largest natural time scales in the system?

**Comment by akaptano** [comment]
Thanks for your thoughts. I was also thinking like the looking at the ratio of the maximum to minimum eigenvalues of the instantaneous Jacobian matrix, and take the max of this ratio over some trajectories, or something to that effect.
